#Jekyll config file

#title of site
name: VA Digital Service

#description of site
description: Redefining the way VA serves veterans

#URL of site, include http://, do not include a trailing slash
# http://localhost
# url: http://127.0.0.1:4000
url: http://department-of-veterans-affairs.github.io/dsva



#files to exclude, array
exclude: [ 'readme.md', 'php' ]

#posts per page
paginate: 1

#number of items in RSS feed
rss_limit: 40

#permalink structure, see https://github.com/mojombo/jekyll/wiki/Permalinks
permalink: /:year/:month/:day/:title/

#whether production or dev, minifies JS, bool
production: true
markdown: redcarpet


sass:
    sass_dir: assets/scss
    style: :compressed
